HexMediaNewsletterMailSent:
    pattern: /sent/{id}/{page}/{sort}/{direction}
    defaults: { _controller: HexmediaNewsletterBundle:AdminSentTo:index, page: 1, sort: obj.id, direction: desc }
    requirements:
        id: \d+
        page: \d+
        direction: asc|desc
    methods: [ GET ]
    options:
        expose: true