HexMediaNewsletterMailAdd:
    pattern: /add
    defaults: { _controller: HexmediaNewsletterBundle:Mail:add }
    methods: [GET]
    options:
        expose: true

HexMediaNewsletterMailCreate:
    pattern: /add
    defaults: { _controller: HexmediaNewsletterBundle:Mail:create }
    methods: [POST]
    options:
        expose: true

HexMediaNewsletterMailEdit:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaNewsletterBundle:Mail:edit }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaNewsletterMailUpdate:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaNewsletterBundle:Mail:update }
    methods: [ PUT, POST ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaNewsletterMailDelete:
    pattern: /{id}/delete
    defaults: { _controller: HexmediaNewsletterBundle:Mail:delete }
    methods: [ POST, PUT, DELETE ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaNewsletterMail:
    pattern: /
    defaults: { _controller: HexmediaNewsletterBundle:Mail:index }
    methods: [ GET ]
    options:
        expose: true

HexMediaNewsletterMailList:
    pattern: /list/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: HexmediaNewsletterBundle:Mail:list, page: 1, sort: id, pageSize: 10, sortDirection: asc }
    requirements:
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    methods: [ GET ]
    options:
        expose: true