<?php

namespace Hexmedia\NewsletterBundle\Repository\Doctrine;

use Hexmedia\AdministratorBundle\Repository\Doctrine\CrudRepository;
use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\NewsletterBundle\Repository\MailRepositoryInterface;

/**
 * newsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends CrudRepository implements MailRepositoryInterface
{
}
