<?php

namespace Hexmedia\NewsletterBundle\Repository\Doctrine;

use Doctrine\ORM\EntityRepository;
use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\NewsletterBundle\Repository\PersonRepositoryInterface;

/**
 * newsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository implements PersonRepositoryInterface
{
    use ListTrait;
}
