<?php

namespace Hexmedia\NewsletterBundle\Repository\Doctrine;

use Doctrine\ORM\EntityRepository;
use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\NewsletterBundle\Repository\SentToRepositoryInterface;

/**
 * SentToRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentToRepository extends EntityRepository implements SentToRepositoryInterface
{
    use ListTrait;

    public function getMailsToSent($limit = 100) {
        $queryBuilder = $this->createQueryBuilder("obj");

        $queryBuilder->where(
            $queryBuilder->expr()->isNull("obj.dateSent")
        );

        $queryBuilder->orderBy("obj.id", "DESC");

        return $queryBuilder->getQuery()->getResult();
    }
}
