<?php

namespace Hexmedia\NewsletterBundle\Repository\Doctrine;

use Hexmedia\AdministratorBundle\Repository\Doctrine\CrudRepository;
use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\NewsletterBundle\Repository\SentToRepositoryInterface;

/**
 * SentToRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentToRepository extends CrudRepository implements SentToRepositoryInterface
{

    public function createListQueryBuilder($alias) {
        $queryBuilder = $this->createQueryBuilder($alias);

        $queryBuilder->innerJoin($alias . '.person', 'person');

        return $queryBuilder;
    }

    public function getMailsToSent($limit = 50) {
        $queryBuilder = $this->createQueryBuilder("obj");

        $queryBuilder->where(
            $queryBuilder->expr()->isNull("obj.dateSent")
        );

        $queryBuilder->orderBy("obj.id", "DESC");
        $queryBuilder->setLimit($limit);

        return $queryBuilder->getQuery()->getResult();
    }
}
